<?php

use App\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::insert([

            [
                'department_id' => 11,
                'subdepartment_id' => null,
                'name' => 'André Mesquita',
                'email' => 'andre.mesquita@masp.org.br',
                'cpf_cnpj' => '27311243858',
                'role' => 'Curador',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 11,
                'subdepartment_id' => null,
                'name' => 'Horrana Santos',
                'email' => 'horrana.santos@masp.org.br',
                'cpf_cnpj' => '10618100709',
                'role' => 'Assistente curatorial',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 18,
                'subdepartment_id' => null,
                'name' => 'Jussara Nascimento',
                'email' => 'jussara.nascimento@masp.org.br',
                'cpf_cnpj' => '39487685871',
                'role' => 'Assistente de relaçoes institucionais',
                'avatar' => 'https://lh4.googleusercontent.com/--GrYP9B7ARk/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rcTFoKG_ITYJrKly_lJ8TFxD3Ti4Q/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Izabela Malzone',
                'email' => 'izabela.malzone@masp.org.br',
                'cpf_cnpj' => '41861475829',
                'role' => 'Produtor Júnior',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Marina de Moura Almeida',
                'email' => 'marina.moura@masp.org.br',
                'cpf_cnpj' => '32119468885',
                'role' => 'Coordenador',
                'avatar' => 'de produçao https://lh4.googleusercontent.com/-p-L5W-jiO2o/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rfL4E0xlqYQprHL5Vy3ErU5SyqkOQ/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Amanda Goes Negri',
                'email' => 'amanda.negri@masp.org.br',
                'cpf_cnpj' => '46782638886',
                'role' => 'Produtor',
                'avatar' => 'júnior https://lh3.googleusercontent.com/a-/AAuE7mDVrup6L4m3GbbUeiJVgInk4mlYFfRIT2r3NsArXA',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Maicon William',
                'email' => 'maicon.ferreira@masp.org.br',
                'cpf_cnpj' => '47585024800',
                'role' => 'Estagiário',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mCtLc27vQWGmN-VCEBxNo9nX8ECXKkrVHrnvxl6Tw',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 18,
                'subdepartment_id' => null,
                'name' => 'Carolina Rossetti',
                'email' => 'carolina.rossetti@masp.org.br',
                'cpf_cnpj' => '36740355886',
                'role' => 'Coordenador de Relaçoes Institucionais',
                'avatar' => 'https://lh5.googleusercontent.com/-LJvOzqNjpCY/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3reI8YdgTnkH3rlPDzyV4ZTqQwJtHg/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Steffania Prata',
                'email' => 'steffania.prata@masp.org.br',
                'cpf_cnpj' => '09662904611',
                'role' => 'Produtor Júnior',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mC7HbxnBpN06NnzBEgxYlr_a1FGhsjcffWDGM6V',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Leonardo Rodrigues Mendes de Souza',
                'email' => 'leonardo.souza@masp.org.br',
                'cpf_cnpj' => '44620264890',
                'role' => 'Estagiário',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mD_A7qINJ5N6o088jhAn5_E7SG9Pn7G_Xhg-fKtRw',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 9,
                'subdepartment_id' => null,
                'name' => 'João Lopes',
                'email' => 'joao.lopes@masp.org.br',
                'cpf_cnpj' => '07947099901',
                'role' => 'Analista Jurídico',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 8,
                'subdepartment_id' => 1,
                'name' => 'Francisco Rodrigues de Sousa',
                'email' => 'francisco.sousa@masp.org.br',
                'cpf_cnpj' => '14778244800',
                'role' => 'Assistente Administrativo',
                'avatar' => 'https://lh5.googleusercontent.com/-NTqIBWLEvlg/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3reMzNYl_9VgXmvHcbS6gYkBmB4mnQ/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 6,
                'name' => 'Keila Clei Ribeiro da Silva',
                'email' => 'keila.silva@masp.org.br',
                'cpf_cnpj' => '33566238856',
                'role' => 'Lider de Segurança',
                'avatar' => 'https://lh3.googleusercontent.com/--JM4b28LmFg/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3revAuHhOAnnuRQUF1ed32e4D4udUQ/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 7,
                'subdepartment_id' => 7,
                'name' => 'Vitor Machado Fernandes',
                'email' => 'vitor.fernandes@masp.org.br',
                'cpf_cnpj' => '41642958808',
                'role' => 'Auxiliar de Tecnologia da Informação',
                'avatar' => 'https://lh6.googleusercontent.com/-g_tzrU7uLyA/AAAAAAAAAAI/AAAAAAAAAAA/AAKWJJN7ulLy2-rCBZQVkhP9hS8K5FhlEQ/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 14,
                'subdepartment_id' => null,
                'name' => 'Miriam Elwing',
                'email' => 'miriam.elwing@masp.org.br',
                'cpf_cnpj' => '11705630820',
                'role' => 'Gerente de Projetos, Infraestrutura e Arquitetura',
                'avatar' => 'https://lh6.googleusercontent.com/-KKcYWUKgLdw/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rc5FfF3t0qtWPWtlvy_mo_i2ODGlA/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 8,
                'subdepartment_id' => 2,
                'name' => 'Marina Sgnotto',
                'email' => 'marina.sgnotto@masp.org.br',
                'cpf_cnpj' => '33764632801',
                'role' => 'Contador',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 8,
                'subdepartment_id' => null,
                'name' => 'Mary Matsumura',
                'email' => 'mary.matsumura@masp.org.br',
                'cpf_cnpj' => '22556156813',
                'role' => 'Gerente Financeiro',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 17,
                'subdepartment_id' => null,
                'name' => 'Renata Toledo',
                'email' => 'renata.toledo@masp.org.br',
                'cpf_cnpj' => '24669315838',
                'role' => 'Coordenador de Recursos Humanos',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 19,
                'subdepartment_id' => null,
                'name' => 'Paula Zoppello',
                'email' => 'paula.zoppello@masp.org.br',
                'cpf_cnpj' => '16530117857',
                'role' => 'Secretaria Plena',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 10,
                'subdepartment_id' => null,
                'name' => 'Alexsandro Silva',
                'email' => 'alexsandro.silva@masp.org.br',
                'cpf_cnpj' => '06735382498',
                'role' => 'Supervisor de Loja',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AOh14GhKsow0ZHMYrvqQY3peVioalJTAehw5LnAvcvZf8w',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Tomás Toledo',
                'email' => 'tomas.toledo@masp.org.br',
                'cpf_cnpj' => '35781102809',
                'role' => 'Curador Chefe',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 2,
                'subdepartment_id' => null,
                'name' => 'Cecília Winter',
                'email' => 'cecilia.winter@masp.org.br',
                'cpf_cnpj' => '29808463843',
                'role' => 'Coordenador de Acervo',
                'avatar' => 'https://lh5.googleusercontent.com/-LRII6pW1QV0/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rfg0kgNaAE9dS1-fok-eqDeC3CIww/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 2,
                'subdepartment_id' => null,
                'name' => 'Erick Santos',
                'email' => 'erick.santos@masp.org.br',
                'cpf_cnpj' => '34862808808',
                'role' => 'Assistente de Conservaçao e Restauro',
                'avatar' => 'https://lh4.googleusercontent.com/-lRptiBLr9H0/AAAAAAAAAAI/AAAAAAAAAAA/AKF05nAt0vwxKGPL0ZnVwvzvalNWlPqOPw/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 3,
                'subdepartment_id' => null,
                'name' => 'Adriana Villela',
                'email' => 'adriana.villela@masp.org.br',
                'cpf_cnpj' => '56313047672',
                'role' => 'Coordenador de Centro de Pesquisa',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Marina Reboucas Martins',
                'email' => 'marina.reboucas@masp.org.br',
                'cpf_cnpj' => '36806622895',
                'role' => 'Produtor Júnior',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mDhjV6l6KtXQEWO3wRxCmX7LAuJTW5l9MYrzdPACw',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 11,
                'subdepartment_id' => null,
                'name' => 'Waldiael Genival Braz da Silva',
                'email' => 'waldiael.braz@masp.org.br',
                'cpf_cnpj' => '31446982882',
                'role' => 'Assistente de Mediaçao e Programas Públicos',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 2,
                'subdepartment_id' => null,
                'name' => 'Nalu Maria',
                'email' => 'nalu.maria@masp.org.br',
                'cpf_cnpj' => '25481840804',
                'role' => 'Supervisor de Acervo',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mBVmlHXAn1NrmQaC-Q-CiBro9-J71FWZJpfirvC',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 1,
                'subdepartment_id' => 10,
                'name' => 'Adriano Pedrosa',
                'email' => 'adriano.pedrosa@masp.org.br',
                'cpf_cnpj' => '81233973720',
                'role' => 'Diretor Artístico',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 1,
                'subdepartment_id' => null,
                'name' => 'Juliana Sá',
                'email' => 'juliana.sa@masp.org.br',
                'cpf_cnpj' => null,
                'role' => null,
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 14,
                'subdepartment_id' => null,
                'name' => 'Leonardo Henrique de Andrade',
                'email' => 'leonardo.henrique@masp.org.br',
                'cpf_cnpj' => '37624734800',
                'role' => 'Assistente de Projetos, Infraestrutura e Arquitetura',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 3,
                'subdepartment_id' => null,
                'name' => 'Bruno Cezar Mesquita Esteves',
                'email' => 'bruno.cezar@masp.org.br',
                'cpf_cnpj' => '34125382808',
                'role' => 'Documentalista',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AOh14Gh3tTJTlkHHciUziOJSaAazNuJ3BRzCZbo2_aRjDg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 3,
                'name' => 'Larissa Miranda Silva',
                'email' => 'larissa.miranda@masp.org.br',
                'cpf_cnpj' => '42698560843',
                'role' => 'Produtor Júnior',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mA7_YiD3xwHGCGl2IqAq88hOXXiMpFHc1v9eXdL',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 2,
                'subdepartment_id' => null,
                'name' => 'Sofia Hennen',
                'email' => 'sofia.hennen@masp.org.br',
                'cpf_cnpj' => '24101701881',
                'role' => 'Supervisor de Conservaçao e Restauro',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 7,
                'subdepartment_id' => 7,
                'name' => 'Marcelo Santos',
                'email' => 'marcelo.santos@masp.org.br',
                'cpf_cnpj' => '32384883844',
                'role' => 'Auxiliar de Tecnologia da Informação',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AOh14GjYrDjKn7ZzBp3FWKGgVnI8e_skBgsPdaa2m99_rg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 3,
                'subdepartment_id' => null,
                'name' => 'Nayara Oliveira',
                'email' => 'nayara.oliveira@masp.org.br',
                'cpf_cnpj' => '22426464860',
                'role' => 'Documentalista',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AOh14GgConD-O7pdjemuOj9jTMqjmaIWaUWahLCzzNVu',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 8,
                'subdepartment_id' => 2,
                'name' => 'Cassiani Santos Aguiar',
                'email' => 'cassiani.aguiar@masp.org.br',
                'cpf_cnpj' => '39930869883',
                'role' => 'Auxiliar de Compras',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 1,
                'subdepartment_id' => 11,
                'name' => 'Fabio Frayha',
                'email' => 'fabio.frayha@masp.org.br',
                'cpf_cnpj' => '04956643675',
                'role' => 'Diretor Financeiro e de Operações',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 15,
                'subdepartment_id' => null,
                'name' => 'Gabriel Di Pietro de Camillo',
                'email' => 'gabriel.camillo@masp.org.br',
                'cpf_cnpj' => '04031659113',
                'role' => 'Analista de Relaçoes Institucionais para Leis de Incentivo',
                'avatar' => 'https://lh6.googleusercontent.com/-HEbOYMOE2Xw/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3re0t8B7yHNAmtprpKQt0-8R2V6Ynw/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Jacqueline da Costa Reis',
                'email' => 'jacqueline.reis@masp.org.br',
                'cpf_cnpj' => '50328914878',
                'role' => 'Aprendiz Administrativo',
                'avatar' => 'https://lh3.googleusercontent.com/-FpJOqiCl6qU/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rfK0G5ashFlwjBBo7KT13yPWjmaaw/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 15,
                'subdepartment_id' => null,
                'name' => 'Giovanna Gray',
                'email' => 'giovanna.gray@masp.org.br',
                'cpf_cnpj' => '43092833813',
                'role' => 'Assistente de Planejamento Estratégico',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 8,
                'subdepartment_id' => 2,
                'name' => 'Paulo Cesar Mafra de Matos',
                'email' => 'paulo.cesar@masp.org.br',
                'cpf_cnpj' => '38941351820',
                'role' => 'Analista Fiscal',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AOh14GgP_mPATqReZ7Fn5xNE50MszcprMGW1ZMD2kUfIsQ',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 8,
                'subdepartment_id' => 1,
                'name' => 'Reinaldo Menezes',
                'email' => 'reinaldo.menezes@masp.org.br',
                'cpf_cnpj' => '11216440743',
                'role' => 'Assistente de Compras',
                'avatar' => 'https://lh6.googleusercontent.com/-ng93ssYkLzE/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rdn6uZ_Ntdc6TdkJ9B_fQptpLIUVQ/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 17,
                'subdepartment_id' => null,
                'name' => 'Katia Valeria Gomes Ferreira',
                'email' => 'katia.gomes@masp.org.br',
                'cpf_cnpj' => '26205497875',
                'role' => 'Analista de Recursos Humanos Pleno',
                'avatar' => 'https://lh3.googleusercontent.com/-Z2JwmaCq8AY/AAAAAAAAAAI/AAAAAAAAAAA/AKF05nDU0RoPz15sb5HSJXd6r3RjIBQvmw/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 2,
                'subdepartment_id' => null,
                'name' => 'Paula Coelho Magalhães de Lima',
                'email' => 'paula.coelho@masp.org.br',
                'cpf_cnpj' => '35270103869',
                'role' => 'Assistente Técnico',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Fernando Gallo',
                'email' => 'fernando.gallo@masp.org.br',
                'cpf_cnpj' => '36912635857',
                'role' => 'Produtor Júnior',
                'avatar' => 'https://lh3.googleusercontent.com/-W2ZTJYaZOKs/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rcjvGwtxh-D6Q-MEuOfPkx65EkwOw/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 7,
                'subdepartment_id' => 7,
                'name' => 'Gabriel Fonseca',
                'email' => 'gabriel.fonseca@masp.org.br',
                'cpf_cnpj' => '07362562616',
                'role' => 'Analista Desenvolvedor',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AOh14GjJ7JrcnhzsfMcBIpGRyfE74t5cbTXTW7QDxmmArQ',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Adriana Rodrigues',
                'email' => 'adriana.rodrigues@masp.org.br',
                'cpf_cnpj' => null,
                'role' => null,
                'avatar' => 'https://lh3.googleusercontent.com/a-/AOh14GjN8zqF9E7-UzrCG8QjyXMjvm6ivr1s92PXo9bJ',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 7,
                'subdepartment_id' => 8,
                'name' => 'Juliana Prado',
                'email' => 'juliana.prado@masp.org.br',
                'cpf_cnpj' => '34954358833',
                'role' => 'Estagiário',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mDpVVJrq5QgOsJIFsdmiNA-bUxEMTRTLVefI6aePw',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 4,
                'subdepartment_id' => null,
                'name' => 'Daniela Cotrim',
                'email' => 'daniela.cotrim@masp.org.br',
                'cpf_cnpj' => '36926940835',
                'role' => 'Supervisor de Comunicaçao e Marketing',
                'avatar' => 'https://lh3.googleusercontent.com/-MEu3eZ7bgBk/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rex3yb1GxUB3DBEowPEGmQnBFciqQ/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 10,
                'subdepartment_id' => null,
                'name' => 'Camila Gomes',
                'email' => 'camila.gomes@masp.org.br',
                'cpf_cnpj' => '12261628781',
                'role' => 'Assistente Comercial',
                'avatar' => 'https://lh6.googleusercontent.com/-TQL7X14bdr0/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rdd4PWwt65swW4sMxRpRbWBv7GSXA/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 8,
                'subdepartment_id' => null,
                'name' => 'Gabriel Brejeiro',
                'email' => 'gabriel.brejeiro@masp.org.br',
                'cpf_cnpj' => '43856883894',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 8,
                'subdepartment_id' => null,
                'name' => 'Maria Lucia de Oliveira Souza',
                'email' => 'maria.lucia@masp.org.br',
                'cpf_cnpj' => '29841995883',
                'role' => 'Assistente Financeiro',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 8,
                'subdepartment_id' => null,
                'name' => 'Marta Nunes',
                'email' => 'marta.nunes@masp.org.br',
                'cpf_cnpj' => '19185279897',
                'role' => 'Assistente Financeiro',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => null,
                'name' => 'Elis Fabro',
                'email' => 'elis.fabro@masp.org.br',
                'cpf_cnpj' => '32216470856',
                'role' => 'Assistente de Operações',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 8,
                'subdepartment_id' => 2,
                'name' => 'Tania Souza',
                'email' => 'tania.souza@masp.org.br',
                'cpf_cnpj' => '34099197832',
                'role' => 'Assistente Fiscal',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mDPC9iP5pWlKwC17W4SWTRCjd3gmEkaSuD3erwo',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 8,
                'subdepartment_id' => 2,
                'name' => 'Ana Paula Moreira',
                'email' => 'ana.moreira@masp.org.br',
                'cpf_cnpj' => '39927742878',
                'role' => 'Assistente Contábil',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 10,
                'subdepartment_id' => null,
                'name' => 'William Ferreira da Silva',
                'email' => 'william.ferreira@masp.org.br',
                'cpf_cnpj' => '35115642808',
                'role' => 'Atendente de Loja',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mAIfguhJDcGQDeZ4OB7SZ3OWMhIq2mqmQMPAN8xsg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 8,
                'subdepartment_id' => 2,
                'name' => 'Fabiana Soares',
                'email' => 'fabiana.soares@masp.org.br',
                'cpf_cnpj' => '28182771838',
                'role' => 'Auxiliar Contábil',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 10,
                'subdepartment_id' => null,
                'name' => 'Alailson Melo',
                'email' => 'alailson.melo@masp.org.br',
                'cpf_cnpj' => '38628107800',
                'role' => 'Assistente de Processos',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mCSSSftTULOTLEgS5pI0EmirzSgkwMJQzbZlqHPaA',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 7,
                'subdepartment_id' => 8,
                'name' => 'Antonio José dos santos',
                'email' => 'antonio.santos@masp.org.br',
                'cpf_cnpj' => '28218157867',
                'role' => 'Marceneiro',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 11,
                'subdepartment_id' => null,
                'name' => 'Eric Augusto Xavier da Silva',
                'email' => 'eric.xavier@masp.org.br',
                'cpf_cnpj' => '40003467848',
                'role' => 'Estagiário',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AOh14GiDCfZKgAlqyrqxUXdcz7Jvx19aw69ufQI7qXkmKw',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 11,
                'subdepartment_id' => null,
                'name' => 'Amanda Carneiro',
                'email' => 'amanda.carneiro@masp.org.br',
                'cpf_cnpj' => '34482540889',
                'role' => 'Curador Assistente',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 3,
                'subdepartment_id' => null,
                'name' => 'Beatriz Yoshito',
                'email' => 'beatriz.yoshito@masp.org.br',
                'cpf_cnpj' => '32970343860',
                'role' => 'Documentalista',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 10,
                'subdepartment_id' => null,
                'name' => 'Bruno Ferreira Silva',
                'email' => 'bruno.silva@masp.org.br',
                'cpf_cnpj' => '47573063857',
                'role' => 'Atendente de Loja',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mBfSAhU1_5SdRiSLY97-vbyLmA2rSSW8wVaf7AjdQ',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 10,
                'subdepartment_id' => null,
                'name' => 'Igor Ferreira Lutero da Silva',
                'email' => 'igor.lutero@masp.org.br',
                'cpf_cnpj' => '40658322842',
                'role' => 'Atendente de Loja',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 7,
                'subdepartment_id' => 8,
                'name' => 'Wilson Marcelino',
                'email' => 'wilson.marcelino@masp.org.br',
                'cpf_cnpj' => '1620970856',
                'role' => 'Coordenador de Manutençao',
                'avatar' => 'https://lh4.googleusercontent.com/-WuAm7hfZ8W8/AAAAAAAAAAI/AAAAAAAAAAA/AKF05nATGxzOJ_KcS86gHaLbMB8RrWtijw/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 3,
                'subdepartment_id' => null,
                'name' => 'Carla Bonomi',
                'email' => 'carla.bonomi@masp.org.br',
                'cpf_cnpj' => '32413067809',
                'role' => 'Bibliotecario',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 3,
                'subdepartment_id' => null,
                'name' => 'Carolina Silva',
                'email' => 'carolina.silva@masp.org.br',
                'cpf_cnpj' => '42570128899',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 3,
                'subdepartment_id' => null,
                'name' => 'Pamella Mazucatto',
                'email' => 'pamella.mazucatto@masp.org.br',
                'cpf_cnpj' => '37735121806',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 3,
                'subdepartment_id' => null,
                'name' => 'Mirna Felix',
                'email' => 'mirna.felix@masp.org.br',
                'cpf_cnpj' => '41384876898',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 11,
                'subdepartment_id' => null,
                'name' => 'Julia Cavazzini',
                'email' => 'julia.cavazzini@masp.org.br',
                'cpf_cnpj' => null,
                'role' => null,
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 10,
                'subdepartment_id' => null,
                'name' => 'Gisele Pedroso do Nascimento',
                'email' => 'gisele.nascimento@masp.org.br',
                'cpf_cnpj' => '37106939854',
                'role' => 'Atendente de Loja',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 4,
                'subdepartment_id' => null,
                'name' => 'Rodrigo Vilano Avelar',
                'email' => 'rodrigo.avelar@masp.org.br',
                'cpf_cnpj' => '41018960899',
                'role' => 'Analista de Comunicação Júnior',
                'avatar' => 'https://lh4.googleusercontent.com/-IqLE850xjq0/AAAAAAAAAAI/AAAAAAAAAAA/AAKWJJM5JDy0xkCtYJOyQjpmqWIljdczDA/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 3,
                'name' => 'Aline Lima',
                'email' => 'aline.lima@masp.org.br',
                'cpf_cnpj' => '42400648808',
                'role' => 'Produtor Júnior',
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mC89j4nO7EIlQkx4kGKD94gZe3hNwGN01Q5XYgh',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 10,
                'subdepartment_id' => null,
                'name' => 'Caique Fernandes',
                'email' => 'caique.fernandes@masp.org.br',
                'cpf_cnpj' => '47216616812',
                'role' => 'Aprendiz Administrativo',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 19,
                'subdepartment_id' => null,
                'name' => 'Brenda Koschel',
                'email' => 'brenda.koschel@masp.org.br',
                'cpf_cnpj' => '42744115835',
                'role' => null,
                'avatar' => 'https://lh3.googleusercontent.com/a-/AAuE7mDJN-VsVUikPHHd6EqcQbU7jYhgYP1DWYP1wJ50',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => null,
                'name' => 'Karina Del Papa',
                'email' => 'karina.delpapa@masp.org.br',
                'cpf_cnpj' => '29587732804',
                'role' => 'Gerente de Operações',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 2,
                'subdepartment_id' => null,
                'name' => 'Erika Litsumi Uehara',
                'email' => 'erika.uehara@masp.org.br',
                'cpf_cnpj' => '26008255844',
                'role' => 'Assistente Técnico',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 2,
                'subdepartment_id' => null,
                'name' => 'Juliana Peixoto',
                'email' => 'juliana.peixoto@masp.org.br',
                'cpf_cnpj' => '30393543889',
                'role' => 'Assistente Técnico',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 2,
                'subdepartment_id' => null,
                'name' => 'Taynara Christal Lima',
                'email' => 'taynara.lima@masp.org.br',
                'cpf_cnpj' => '47925687819',
                'role' => 'Aprendiz Administrativo',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 4,
                'subdepartment_id' => null,
                'name' => 'Gabriela Valdanha de Araujo',
                'email' => 'gabriela.valdanha@masp.org.br',
                'cpf_cnpj' => '22973703859',
                'role' => 'Analista de Comunicação Júnior',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 4,
                'subdepartment_id' => null,
                'name' => 'Fernando Netto',
                'email' => 'fernando.netto@masp.org.br',
                'cpf_cnpj' => '43247678824',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Fernando Oliva',
                'email' => 'fernando.oliva@masp.org.br',
                'cpf_cnpj' => '13601850893',
                'role' => 'Curador',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Isabella Rjeille Cordeiro',
                'email' => 'isabella.rjeille@masp.org.br',
                'cpf_cnpj' => '35934996819',
                'role' => 'Curador',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Olivia Cecilia Manuel Ardui',
                'email' => 'olivia.ardui@masp.org.br',
                'cpf_cnpj' => '23625725878',
                'role' => 'Curador Assistente',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Mariana Trevas',
                'email' => 'mariana.trevas@masp.org.br',
                'cpf_cnpj' => '21998336824',
                'role' => 'Assistente Editorial',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Guilherme Perez Giufrida',
                'email' => 'guilherme.giufrida@masp.org.br',
                'cpf_cnpj' => '34403964877',
                'role' => 'Assistente Curatorial',
                'avatar' => 'https://lh5.googleusercontent.com/-Cm-01FuisPI/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rc97eBG7d9Jw8t_13-zdLNWsBQhfw/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Ana Carolina Pais Pellegrini',
                'email' => 'ana.pellegrini@masp.org.br',
                'cpf_cnpj' => '43513163819',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Leonardo Antiqueira',
                'email' => 'leonardo.antiqueira@masp.org.br',
                'cpf_cnpj' => '34347748825',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Matheus Araujo Andrade Costa',
                'email' => 'matheus.costa@masp.org.br',
                'cpf_cnpj' => '11889894648',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Bruno Gomes Rodrigues',
                'email' => 'bruno.gomes@masp.org.br',
                'cpf_cnpj' => '2876266016',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Mayara Soares',
                'email' => 'mayara.soares@masp.org.br',
                'cpf_cnpj' => '47270687889',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Gabriela Gotoda',
                'email' => 'gabriela.gotoda@masp.org.br',
                'cpf_cnpj' => '44166942883',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 6,
                'subdepartment_id' => null,
                'name' => 'Clau Lima',
                'email' => 'clau.lima@masp.org.br',
                'cpf_cnpj' => '41625159803',
                'role' => 'Auxiliar de Design',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 6,
                'subdepartment_id' => null,
                'name' => 'Barbara Catta Preta Lima',
                'email' => 'barbara.lima@masp.org.br',
                'cpf_cnpj' => '44120565890',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 19,
                'subdepartment_id' => null,
                'name' => 'Renan Ferreira Dantas',
                'email' => 'renan.dantas@masp.org.br',
                'cpf_cnpj' => '42630221814',
                'role' => 'Mensageiro',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Israel Serpa Pereira',
                'email' => 'israel.pereira@masp.org.br',
                'cpf_cnpj' => '27463187845',
                'role' => 'Assistente de Supervisão',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Sidiclei dos Santos',
                'email' => 'sidiclei.santos@masp.org.br',
                'cpf_cnpj' => '73446807500',
                'role' => 'Recepcionista',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Jose Pereira da Silva',
                'email' => 'jose.silva@masp.org.br',
                'cpf_cnpj' => '95520830878',
                'role' => 'Orientador de Público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Michel Fernando Ramos Favacho',
                'email' => 'michel.favacho@masp.org.br',
                'cpf_cnpj' => '71445510278',
                'role' => 'Orientador de Público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 4,
                'name' => 'Larissa Rafaela da Biscolo',
                'email' => 'rafaela.biscolo@masp.org.br',
                'cpf_cnpj' => '23035713839',
                'role' => 'Líder de Bilheteria',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => null,
                'name' => 'Vinicius Flauaus',
                'email' => 'vicinius.flauaus@masp.org.br',
                'cpf_cnpj' => '38861492851',
                'role' => 'Supervisor de Operações',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Marcello Martins Israel',
                'email' => 'marcello.israel@masp.org.br',
                'cpf_cnpj' => '26514236880',
                'role' => 'Orientador de Público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Dannyele Cavalcante Melo',
                'email' => 'dannyele.cavalcante@masp.org.br',
                'cpf_cnpj' => '7178745401',
                'role' => 'Recepcionista',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Renan Preto de Oliveira',
                'email' => 'renan.oliveira@masp.org.br',
                'cpf_cnpj' => '37134846865',
                'role' => 'Orientador de Público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Amanda Marques Paschoal',
                'email' => 'amanda.paschoal@masp.org.br',
                'cpf_cnpj' => '5440415505',
                'role' => 'Orientador de Público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Napolazar Rezende',
                'email' => 'napolazar.rezende@masp.org.br',
                'cpf_cnpj' => '37417353886',
                'role' => 'Orientador de Público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 4,
                'name' => 'Marcia da Silva Batista',
                'email' => 'marcia.batista@masp.org.br',
                'cpf_cnpj' => '29470028813',
                'role' => 'Bilheteiro',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Thais Oliveira Chagas',
                'email' => 'thais.chagas@masp.org.br',
                'cpf_cnpj' => '47427937813',
                'role' => 'Orientador de Público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Fernanda Vieira Araujo',
                'email' => 'fernanda.araujo@masp.org.br',
                'cpf_cnpj' => '44943246800',
                'role' => 'Orientador de Público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Nathalia Ribeiro',
                'email' => 'nathalia.ribeiro@masp.org.br',
                'cpf_cnpj' => '46726129882',
                'role' => 'Orientador de Público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Matheus do Nascimento Sousa',
                'email' => 'matheus.sousa@masp.org.br',
                'cpf_cnpj' => '46073875843',
                'role' => 'Orientador de Público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Isabelle Carmo',
                'email' => 'isabelle.carmo@masp.org.br',
                'cpf_cnpj' => '45599803813',
                'role' => 'Orientador de Público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'Rodrigo Ferreira',
                'email' => 'rodrigo.ferreira@masp.org.br',
                'cpf_cnpj' => '36310803875',
                'role' => 'Orientador de público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'FLAVIA MARIA BARBOSA GIACONTO',
                'email' => 'flavia.giaconto@masp.org.br',
                'cpf_cnpj' => '88008851449',
                'role' => 'Orientador de Público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'GIONNI BOARETO VARGAS',
                'email' => 'gionni.vargas@masp.org.br',
                'cpf_cnpj' => '45165598896',
                'role' => 'Orientador de público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'MARION SANTOS NOVAIS',
                'email' => 'marion.novais@masp.org.br',
                'cpf_cnpj' => '52986080510',
                'role' => 'Orientador de público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'ANDRESSA RODRIGUES DA SILVA',
                'email' => 'andressa.silva@masp.org.br',
                'cpf_cnpj' => '36997012809',
                'role' => 'Orientador de público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // [
            //     'department_id' => ,
            //     'subdepartment_id' => null,
            //     'name' => 'BIANCA MOURA',
            //     'email' => 'bianca.moura@masp.org.br',
            //     'cpf_cnpj' => '50851962874',
            //     'role' => 'Aprendiz administrativo',
            //     'avatar' => null,
            //     'registration_code' => null,
            //     'status' => Carbon::now(),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'AYLA ROCHA LOPES',
                'email' => 'ayla.lopes@masp.org.br',
                'cpf_cnpj' => '48058134821',
                'role' => 'Orientador de público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 5,
                'name' => 'JULIO JOVANOLLI',
                'email' => 'julio.jovanolli@masp.org.br',
                'cpf_cnpj' => '41913704807',
                'role' => 'Orientador de público',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // [
            //     'department_id' => ,
            //     'subdepartment_id' => null,
            //     'name' => 'RAFAEL BARROSO DE CARVALHO',
            //     'email' => 'rafael.carvalho@masp.org.br',
            //     'cpf_cnpj' => '46487083852',
            //     'role' => 'Estagiário',
            //     'avatar' => null,
            //     'registration_code' => null,
            //     'status' => Carbon::now(),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],

            // [
            //     'department_id' => ,
            //     'subdepartment_id' => null,
            //     'name' => 'SIDNEY SANTOS ZONATTO',
            //     'email' => 'sidney.zonatto@masp.org.br',
            //     'cpf_cnpj' => '49127825809',
            //     'role' => 'Estagiário',
            //     'avatar' => null,
            //     'registration_code' => null,
            //     'status' => Carbon::now(),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],

            // [
            //     'department_id' => ,
            //     'subdepartment_id' => null,
            //     'name' => 'PEDRO CARVALHO ALVES',
            //     'email' => 'pedro.alves@masp.org.br',
            //     'cpf_cnpj' => '35792073856',
            //     'role' => 'Estagiário',
            //     'avatar' => null,
            //     'registration_code' => null,
            //     'status' => Carbon::now(),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],

            // [
            //     'department_id' => ,
            //     'subdepartment_id' => null,
            //     'name' => 'VITORIA HELOISA AZEVEDO SANTOS',
            //     'email' => 'vitoria.santos@masp.org.br',
            //     'cpf_cnpj' => '45582919813',
            //     'role' => 'Estagiário',
            //     'avatar' => null,
            //     'registration_code' => null,
            //     'status' => Carbon::now(),
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],

            [
                'department_id' => 15,
                'subdepartment_id' => null,
                'name' => 'FERNANDA FERRAZ BONINI',
                'email' => 'fernanda.bonini@masp.org.br',
                'cpf_cnpj' => '39414102884',
                'role' => 'Supervisor de Planejamento Estratégico',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 7,
                'subdepartment_id' => 8,
                'name' => 'LUIZ APARECIDO DOS SANTOS',
                'email' => null,
                'cpf_cnpj' => '04621275836',
                'role' => 'Eletricista Sênior',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 7,
                'subdepartment_id' => 8,
                'name' => 'GILBERTO SOUSA BEZERRA',
                'email' => null,
                'cpf_cnpj' => '07683720895',
                'role' => 'Encanador',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 7,
                'subdepartment_id' => 8,
                'name' => 'EWERTON CAVEDEN',
                'email' => null,
                'cpf_cnpj' => '38187478810',
                'role' => 'Eletricista Júnior',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 15,
                'subdepartment_id' => null,
                'name' => 'ISABELLA SOUZA GAMA',
                'email' => 'isabella.gama@masp.org.br',
                'cpf_cnpj' => '22796432866',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 9,
                'subdepartment_id' => null,
                'name' => 'FERNANDO NAMUR',
                'email' => 'fernando.namur@masp.org.br',
                'cpf_cnpj' => '41642760889',
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 12,
                'subdepartment_id' => 6,
                'name' => 'SHEILA DANIELE RODRIGUES ALVES',
                'email' => 'bombeiros@masp.org.br',
                'cpf_cnpj' => '36215213802',
                'role' => 'Bombeiro Civil',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 17,
                'subdepartment_id' => null,
                'name' => 'Paulo Silva',
                'email' => 'paulo.silva@masp.org.br',
                'cpf_cnpj' => null,
                'role' => null,
                'avatar' => 'https://lh3.googleusercontent.com/a-/AOh14Ghjuxiz6CrNC6wXMLtFjOV86QZTUcHfECfzyTD7',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 7,
                'subdepartment_id' => null,
                'name' => 'Valdir Ferreira',
                'email' => 'valdir.ferreira@masp.org.br',
                'cpf_cnpj' => null,
                'role' => null,
                'avatar' => 'https://lh5.googleusercontent.com/-pnF7XoQoWiM/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3reHhbUUWnEFUTH9Xo2ypbjXYNu7tA/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 2,
                'subdepartment_id' => null,
                'name' => 'Aline Assumpção',
                'email' => 'aline.assumpcao@masp.org.br',
                'cpf_cnpj' => null,
                'role' => null,
                'avatar' => 'https://lh4.googleusercontent.com/-7weN44H3zwA/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rdIG3IvpjU5BqT92m2ctm7nikUp6A/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 7,
                'subdepartment_id' => 8,
                'name' => 'Romulo Alberto de Oliveira',
                'email' => null,
                'cpf_cnpj' => '40944805876',
                'role' => 'Eletricista',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Laura Cosendey',
                'email' => 'laura.cosendey@masp.org.br',
                'cpf_cnpj' => null,
                'role' => null,
                'avatar' => 'https://lh4.googleusercontent.com/-qUTgexJv-sU/AAAAAAAAAAI/AAAAAAAAAAA/AKF05nDJHLH1eU0vwbZRbHdZ4-vzzctxlg/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 11,
                'subdepartment_id' => null,
                'name' => 'Yasmine Lima',
                'email' => 'yasmine.lima@masp.org.br',
                'cpf_cnpj' => null,
                'role' => null,
                'avatar' => 'https://lh3.googleusercontent.com/a-/AOh14Gg4b1qPO9dLNOLCJqXoyACt35BsTpuL-nNV-SPE',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 4,
                'subdepartment_id' => null,
                'name' => 'Mariana Marques',
                'email' => 'mariana.marques@masp.org.br',
                'cpf_cnpj' => null,
                'role' => null,
                'avatar' => 'https://lh5.googleusercontent.com/-TMb3IX2uC3c/AAAAAAAAAAI/AAAAAAAAAAA/AKF05nBItTl7T1wGHashsk-GEEkZJAb6TQ/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 2,
                'subdepartment_id' => null,
                'name' => 'Bianca Saijo',
                'email' => 'bianca.saijo@masp.org.br',
                'cpf_cnpj' => null,
                'role' => null,
                'avatar' => 'https://lh6.googleusercontent.com/-c9GS3qu4wCM/AAAAAAAAAAI/AAAAAAAAAAA/AKF05nAkcF4WY2aPnd5r1IOukRCPWMVMvg/photo.jpg',
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 18,
                'subdepartment_id' => null,
                'name' => 'Lais Almeida Santos',
                'email' => 'lais.almeida@masp.org.br',
                'cpf_cnpj' => '41443514837',
                'role' => null,
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 2,
                'subdepartment_id' => null,
                'name' => 'Felipe Lucena',
                'email' => 'felipe.lucena@masp.org.br',
                'cpf_cnpj' => null,
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Laura Consendey',
                'email' => 'laura.consendey@masp.org.br',
                'cpf_cnpj' => null,
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 5,
                'subdepartment_id' => null,
                'name' => 'Mayara Santos',
                'email' => 'mayara.soares@masp.org.br',
                'cpf_cnpj' => null,
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 6,
                'subdepartment_id' => null,
                'name' => 'Paula Tinoco',
                'email' => 'paula.tinoco@masp.org.br',
                'cpf_cnpj' => null,
                'role' => 'Gestão',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 6,
                'subdepartment_id' => null,
                'name' => 'Guilherme Pacola',
                'email' => 'desingner3@masp.org.br',
                'cpf_cnpj' => null,
                'role' => 'Designer',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 11,
                'subdepartment_id' => null,
                'name' => 'Stela Martins',
                'email' => 'stela.martins@masp.org.br',
                'cpf_cnpj' => null,
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 13,
                'subdepartment_id' => null,
                'name' => 'Juliana Ziebell',
                'email' => 'juliana.ziebell@masp.org.br',
                'cpf_cnpj' => null,
                'role' => 'Arquiteta',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'department_id' => 19,
                'subdepartment_id' => null,
                'name' => 'Debora Ferreira',
                'email' => 'debora.ferreira@masp.org.br',
                'cpf_cnpj' => null,
                'role' => 'Estagiário',
                'avatar' => null,
                'registration_code' => null,
                'status' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}
